//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WorflowCreation {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckIfUserExistResult", Namespace="http://schemas.datacontract.org/2004/07/WorkflowServices")]
    public enum CheckIfUserExistResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICE_ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATA_ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXIST = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_EXIST = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_TESTED = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorflowCreation.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateAccount", ReplyAction="http://tempuri.org/IService/CreateAccountResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="UserExist")]
        Client.WorflowCreation.CheckIfUserExistResult CreateAccount(string Prenom, string Nom, string Email, string Phone, string Password);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GuidRequest n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GuidRequest", ReplyAction="http://tempuri.org/IService/GuidRequestResponse")]
        Client.WorflowCreation.GuidRequestResponse GuidRequest(Client.WorflowCreation.GuidRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuidRequestRequest {
        
        public GuidRequestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuidRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuidRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid SessionID;
        
        public GuidRequestResponse() {
        }
        
        public GuidRequestResponse(System.Guid UserID, System.Guid SessionID) {
            this.UserID = UserID;
            this.SessionID = SessionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.WorflowCreation.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.WorflowCreation.IService>, Client.WorflowCreation.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.WorflowCreation.CheckIfUserExistResult CreateAccount(string Prenom, string Nom, string Email, string Phone, string Password) {
            return base.Channel.CreateAccount(Prenom, Nom, Email, Phone, Password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.WorflowCreation.GuidRequestResponse Client.WorflowCreation.IService.GuidRequest(Client.WorflowCreation.GuidRequestRequest request) {
            return base.Channel.GuidRequest(request);
        }
        
        public System.Guid GuidRequest(out System.Guid SessionID) {
            Client.WorflowCreation.GuidRequestRequest inValue = new Client.WorflowCreation.GuidRequestRequest();
            Client.WorflowCreation.GuidRequestResponse retVal = ((Client.WorflowCreation.IService)(this)).GuidRequest(inValue);
            SessionID = retVal.SessionID;
            return retVal.UserID;
        }
    }
}
