//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("DADModel", "FK_ADRESSE_CLIENT_CLIENT", "CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.CLIENT), "ADRESSE_CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.ADRESSE_CLIENT))]
[assembly: EdmRelationshipAttribute("DADModel", "FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "ADRESSE_CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.ADRESSE_CLIENT), "COMMANDE_CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.COMMANDE_CLIENT))]
[assembly: EdmRelationshipAttribute("DADModel", "FK_CATEGORIE_CATEGORIE", "CATEGORIE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataService.CATEGORIE), "CATEGORIE1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.CATEGORIE))]
[assembly: EdmRelationshipAttribute("DADModel", "FK_COMMANDE_CLIENT_CLIENT", "CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.CLIENT), "COMMANDE_CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.COMMANDE_CLIENT))]
[assembly: EdmRelationshipAttribute("DADModel", "FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.COMMANDE_CLIENT), "COMMANDE_FOURNISSEUR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.COMMANDE_FOURNISSEUR))]
[assembly: EdmRelationshipAttribute("DADModel", "FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "FOURNISSEUR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.FOURNISSEUR), "COMMANDE_FOURNISSEUR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.COMMANDE_FOURNISSEUR))]
[assembly: EdmRelationshipAttribute("DADModel", "FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDE_FOURNISSEUR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.COMMANDE_FOURNISSEUR), "COMMANDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.COMMANDER), true)]
[assembly: EdmRelationshipAttribute("DADModel", "FK_COMMANDER_PRODUIT", "PRODUIT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataService.PRODUIT), "COMMANDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.COMMANDER), true)]
[assembly: EdmRelationshipAttribute("DADModel", "APPARTIENT", "CATEGORIE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.CATEGORIE), "PRODUIT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataService.PRODUIT))]

#endregion

namespace DataService
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class DADEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet DADEntities à l'aide de la chaîne de connexion trouvée dans la section 'DADEntities' du fichier de configuration d'application.
        /// </summary>
        public DADEntities() : base("name=DADEntities", "DADEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet DADEntities.
        /// </summary>
        public DADEntities(string connectionString) : base(connectionString, "DADEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet DADEntities.
        /// </summary>
        public DADEntities(EntityConnection connection) : base(connection, "DADEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ADRESSE_CLIENT> ADRESSE_CLIENT
        {
            get
            {
                if ((_ADRESSE_CLIENT == null))
                {
                    _ADRESSE_CLIENT = base.CreateObjectSet<ADRESSE_CLIENT>("ADRESSE_CLIENT");
                }
                return _ADRESSE_CLIENT;
            }
        }
        private ObjectSet<ADRESSE_CLIENT> _ADRESSE_CLIENT;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<CATEGORIE> CATEGORIE
        {
            get
            {
                if ((_CATEGORIE == null))
                {
                    _CATEGORIE = base.CreateObjectSet<CATEGORIE>("CATEGORIE");
                }
                return _CATEGORIE;
            }
        }
        private ObjectSet<CATEGORIE> _CATEGORIE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<CLIENT> CLIENT
        {
            get
            {
                if ((_CLIENT == null))
                {
                    _CLIENT = base.CreateObjectSet<CLIENT>("CLIENT");
                }
                return _CLIENT;
            }
        }
        private ObjectSet<CLIENT> _CLIENT;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<COMMANDE_CLIENT> COMMANDE_CLIENT
        {
            get
            {
                if ((_COMMANDE_CLIENT == null))
                {
                    _COMMANDE_CLIENT = base.CreateObjectSet<COMMANDE_CLIENT>("COMMANDE_CLIENT");
                }
                return _COMMANDE_CLIENT;
            }
        }
        private ObjectSet<COMMANDE_CLIENT> _COMMANDE_CLIENT;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<COMMANDE_FOURNISSEUR> COMMANDE_FOURNISSEUR
        {
            get
            {
                if ((_COMMANDE_FOURNISSEUR == null))
                {
                    _COMMANDE_FOURNISSEUR = base.CreateObjectSet<COMMANDE_FOURNISSEUR>("COMMANDE_FOURNISSEUR");
                }
                return _COMMANDE_FOURNISSEUR;
            }
        }
        private ObjectSet<COMMANDE_FOURNISSEUR> _COMMANDE_FOURNISSEUR;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<COMMANDER> COMMANDER
        {
            get
            {
                if ((_COMMANDER == null))
                {
                    _COMMANDER = base.CreateObjectSet<COMMANDER>("COMMANDER");
                }
                return _COMMANDER;
            }
        }
        private ObjectSet<COMMANDER> _COMMANDER;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<FOURNISSEUR> FOURNISSEUR
        {
            get
            {
                if ((_FOURNISSEUR == null))
                {
                    _FOURNISSEUR = base.CreateObjectSet<FOURNISSEUR>("FOURNISSEUR");
                }
                return _FOURNISSEUR;
            }
        }
        private ObjectSet<FOURNISSEUR> _FOURNISSEUR;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<PRODUIT> PRODUIT
        {
            get
            {
                if ((_PRODUIT == null))
                {
                    _PRODUIT = base.CreateObjectSet<PRODUIT>("PRODUIT");
                }
                return _PRODUIT;
            }
        }
        private ObjectSet<PRODUIT> _PRODUIT;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ADRESSE_CLIENT. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToADRESSE_CLIENT(ADRESSE_CLIENT aDRESSE_CLIENT)
        {
            base.AddObject("ADRESSE_CLIENT", aDRESSE_CLIENT);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet CATEGORIE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCATEGORIE(CATEGORIE cATEGORIE)
        {
            base.AddObject("CATEGORIE", cATEGORIE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet CLIENT. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCLIENT(CLIENT cLIENT)
        {
            base.AddObject("CLIENT", cLIENT);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet COMMANDE_CLIENT. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCOMMANDE_CLIENT(COMMANDE_CLIENT cOMMANDE_CLIENT)
        {
            base.AddObject("COMMANDE_CLIENT", cOMMANDE_CLIENT);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet COMMANDE_FOURNISSEUR. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCOMMANDE_FOURNISSEUR(COMMANDE_FOURNISSEUR cOMMANDE_FOURNISSEUR)
        {
            base.AddObject("COMMANDE_FOURNISSEUR", cOMMANDE_FOURNISSEUR);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet COMMANDER. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCOMMANDER(COMMANDER cOMMANDER)
        {
            base.AddObject("COMMANDER", cOMMANDER);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet FOURNISSEUR. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToFOURNISSEUR(FOURNISSEUR fOURNISSEUR)
        {
            base.AddObject("FOURNISSEUR", fOURNISSEUR);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet PRODUIT. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPRODUIT(PRODUIT pRODUIT)
        {
            base.AddObject("PRODUIT", pRODUIT);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="ADRESSE_CLIENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ADRESSE_CLIENT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ADRESSE_CLIENT.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="adresse">Valeur initiale de la propriété adresse.</param>
        /// <param name="ville">Valeur initiale de la propriété ville.</param>
        /// <param name="code_postal">Valeur initiale de la propriété code_postal.</param>
        /// <param name="pays">Valeur initiale de la propriété pays.</param>
        public static ADRESSE_CLIENT CreateADRESSE_CLIENT(global::System.Guid id, global::System.String adresse, global::System.String ville, global::System.String code_postal, global::System.String pays)
        {
            ADRESSE_CLIENT aDRESSE_CLIENT = new ADRESSE_CLIENT();
            aDRESSE_CLIENT.id = id;
            aDRESSE_CLIENT.adresse = adresse;
            aDRESSE_CLIENT.ville = ville;
            aDRESSE_CLIENT.code_postal = code_postal;
            aDRESSE_CLIENT.pays = pays;
            return aDRESSE_CLIENT;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ville
        {
            get
            {
                return _ville;
            }
            set
            {
                OnvilleChanging(value);
                ReportPropertyChanging("ville");
                _ville = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ville");
                OnvilleChanged();
            }
        }
        private global::System.String _ville;
        partial void OnvilleChanging(global::System.String value);
        partial void OnvilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String code_postal
        {
            get
            {
                return _code_postal;
            }
            set
            {
                Oncode_postalChanging(value);
                ReportPropertyChanging("code_postal");
                _code_postal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("code_postal");
                Oncode_postalChanged();
            }
        }
        private global::System.String _code_postal;
        partial void Oncode_postalChanging(global::System.String value);
        partial void Oncode_postalChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pays
        {
            get
            {
                return _pays;
            }
            set
            {
                OnpaysChanging(value);
                ReportPropertyChanging("pays");
                _pays = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pays");
                OnpaysChanged();
            }
        }
        private global::System.String _pays;
        partial void OnpaysChanging(global::System.String value);
        partial void OnpaysChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_ADRESSE_CLIENT_CLIENT", "CLIENT")]
        public CLIENT CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("DADModel.FK_ADRESSE_CLIENT_CLIENT", "CLIENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("DADModel.FK_ADRESSE_CLIENT_CLIENT", "CLIENT").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENT> CLIENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("DADModel.FK_ADRESSE_CLIENT_CLIENT", "CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENT>("DADModel.FK_ADRESSE_CLIENT_CLIENT", "CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "COMMANDE_CLIENT")]
        public EntityCollection<COMMANDE_CLIENT> COMMANDE_CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "COMMANDE_CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "COMMANDE_CLIENT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="CATEGORIE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CATEGORIE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet CATEGORIE.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        public static CATEGORIE CreateCATEGORIE(global::System.Guid id, global::System.String nom)
        {
            CATEGORIE cATEGORIE = new CATEGORIE();
            cATEGORIE.id = id;
            cATEGORIE.nom = nom;
            return cATEGORIE;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_CATEGORIE_CATEGORIE", "CATEGORIE1")]
        public EntityCollection<CATEGORIE> CATEGORIE1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CATEGORIE>("DADModel.FK_CATEGORIE_CATEGORIE", "CATEGORIE1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CATEGORIE>("DADModel.FK_CATEGORIE_CATEGORIE", "CATEGORIE1", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_CATEGORIE_CATEGORIE", "CATEGORIE")]
        public CATEGORIE CATEGORIE2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIE>("DADModel.FK_CATEGORIE_CATEGORIE", "CATEGORIE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIE>("DADModel.FK_CATEGORIE_CATEGORIE", "CATEGORIE").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CATEGORIE> CATEGORIE2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIE>("DADModel.FK_CATEGORIE_CATEGORIE", "CATEGORIE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CATEGORIE>("DADModel.FK_CATEGORIE_CATEGORIE", "CATEGORIE", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "APPARTIENT", "PRODUIT")]
        public EntityCollection<PRODUIT> PRODUIT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PRODUIT>("DADModel.APPARTIENT", "PRODUIT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PRODUIT>("DADModel.APPARTIENT", "PRODUIT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="CLIENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet CLIENT.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété prenom.</param>
        /// <param name="phone">Valeur initiale de la propriété phone.</param>
        /// <param name="email">Valeur initiale de la propriété email.</param>
        /// <param name="password">Valeur initiale de la propriété password.</param>
        public static CLIENT CreateCLIENT(global::System.Guid id, global::System.String nom, global::System.String prenom, global::System.String phone, global::System.String email, global::System.String password)
        {
            CLIENT cLIENT = new CLIENT();
            cLIENT.id = id;
            cLIENT.nom = nom;
            cLIENT.prenom = prenom;
            cLIENT.phone = phone;
            cLIENT.email = email;
            cLIENT.password = password;
            return cLIENT;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_ADRESSE_CLIENT_CLIENT", "ADRESSE_CLIENT")]
        public EntityCollection<ADRESSE_CLIENT> ADRESSE_CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ADRESSE_CLIENT>("DADModel.FK_ADRESSE_CLIENT_CLIENT", "ADRESSE_CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ADRESSE_CLIENT>("DADModel.FK_ADRESSE_CLIENT_CLIENT", "ADRESSE_CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_CLIENT_CLIENT", "COMMANDE_CLIENT")]
        public EntityCollection<COMMANDE_CLIENT> COMMANDE_CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_CLIENT", "COMMANDE_CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_CLIENT", "COMMANDE_CLIENT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="COMMANDE_CLIENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COMMANDE_CLIENT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet COMMANDE_CLIENT.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="date">Valeur initiale de la propriété date.</param>
        /// <param name="prix_total">Valeur initiale de la propriété prix_total.</param>
        public static COMMANDE_CLIENT CreateCOMMANDE_CLIENT(global::System.Guid id, global::System.DateTime date, global::System.Decimal prix_total)
        {
            COMMANDE_CLIENT cOMMANDE_CLIENT = new COMMANDE_CLIENT();
            cOMMANDE_CLIENT.id = id;
            cOMMANDE_CLIENT.date = date;
            cOMMANDE_CLIENT.prix_total = prix_total;
            return cOMMANDE_CLIENT;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prix_total
        {
            get
            {
                return _prix_total;
            }
            set
            {
                Onprix_totalChanging(value);
                ReportPropertyChanging("prix_total");
                _prix_total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prix_total");
                Onprix_totalChanged();
            }
        }
        private global::System.Decimal _prix_total;
        partial void Onprix_totalChanging(global::System.Decimal value);
        partial void Onprix_totalChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "ADRESSE_CLIENT")]
        public ADRESSE_CLIENT ADRESSE_CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADRESSE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "ADRESSE_CLIENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADRESSE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "ADRESSE_CLIENT").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ADRESSE_CLIENT> ADRESSE_CLIENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADRESSE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "ADRESSE_CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ADRESSE_CLIENT>("DADModel.FK_COMMANDE_CLIENT_ADRESSE_CLIENT", "ADRESSE_CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_CLIENT_CLIENT", "CLIENT")]
        public CLIENT CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("DADModel.FK_COMMANDE_CLIENT_CLIENT", "CLIENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("DADModel.FK_COMMANDE_CLIENT_CLIENT", "CLIENT").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENT> CLIENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("DADModel.FK_COMMANDE_CLIENT_CLIENT", "CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENT>("DADModel.FK_COMMANDE_CLIENT_CLIENT", "CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_FOURNISSEUR")]
        public EntityCollection<COMMANDE_FOURNISSEUR> COMMANDE_FOURNISSEUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_FOURNISSEUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_FOURNISSEUR", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="COMMANDE_FOURNISSEUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COMMANDE_FOURNISSEUR : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet COMMANDE_FOURNISSEUR.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="date_generation">Valeur initiale de la propriété date_generation.</param>
        /// <param name="prix_total">Valeur initiale de la propriété prix_total.</param>
        public static COMMANDE_FOURNISSEUR CreateCOMMANDE_FOURNISSEUR(global::System.Guid id, global::System.DateTime date_generation, global::System.Decimal prix_total)
        {
            COMMANDE_FOURNISSEUR cOMMANDE_FOURNISSEUR = new COMMANDE_FOURNISSEUR();
            cOMMANDE_FOURNISSEUR.id = id;
            cOMMANDE_FOURNISSEUR.date_generation = date_generation;
            cOMMANDE_FOURNISSEUR.prix_total = prix_total;
            return cOMMANDE_FOURNISSEUR;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_generation
        {
            get
            {
                return _date_generation;
            }
            set
            {
                Ondate_generationChanging(value);
                ReportPropertyChanging("date_generation");
                _date_generation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_generation");
                Ondate_generationChanged();
            }
        }
        private global::System.DateTime _date_generation;
        partial void Ondate_generationChanging(global::System.DateTime value);
        partial void Ondate_generationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_validation
        {
            get
            {
                return _date_validation;
            }
            set
            {
                Ondate_validationChanging(value);
                ReportPropertyChanging("date_validation");
                _date_validation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_validation");
                Ondate_validationChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_validation;
        partial void Ondate_validationChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_validationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_expedition
        {
            get
            {
                return _date_expedition;
            }
            set
            {
                Ondate_expeditionChanging(value);
                ReportPropertyChanging("date_expedition");
                _date_expedition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_expedition");
                Ondate_expeditionChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_expedition;
        partial void Ondate_expeditionChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_expeditionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_reception
        {
            get
            {
                return _date_reception;
            }
            set
            {
                Ondate_receptionChanging(value);
                ReportPropertyChanging("date_reception");
                _date_reception = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_reception");
                Ondate_receptionChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_reception;
        partial void Ondate_receptionChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_receptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> duree_expedition_estimee
        {
            get
            {
                return _duree_expedition_estimee;
            }
            set
            {
                Onduree_expedition_estimeeChanging(value);
                ReportPropertyChanging("duree_expedition_estimee");
                _duree_expedition_estimee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duree_expedition_estimee");
                Onduree_expedition_estimeeChanged();
            }
        }
        private Nullable<global::System.Decimal> _duree_expedition_estimee;
        partial void Onduree_expedition_estimeeChanging(Nullable<global::System.Decimal> value);
        partial void Onduree_expedition_estimeeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prix_total
        {
            get
            {
                return _prix_total;
            }
            set
            {
                Onprix_totalChanging(value);
                ReportPropertyChanging("prix_total");
                _prix_total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prix_total");
                Onprix_totalChanged();
            }
        }
        private global::System.Decimal _prix_total;
        partial void Onprix_totalChanging(global::System.Decimal value);
        partial void Onprix_totalChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_CLIENT")]
        public COMMANDE_CLIENT COMMANDE_CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_CLIENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_CLIENT").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<COMMANDE_CLIENT> COMMANDE_CLIENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<COMMANDE_CLIENT>("DADModel.FK_COMMANDE_FOURNISSEUR_COMMANDE_CLIENT", "COMMANDE_CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "FOURNISSEUR")]
        public FOURNISSEUR FOURNISSEUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "FOURNISSEUR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "FOURNISSEUR").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FOURNISSEUR> FOURNISSEURReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "FOURNISSEUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "FOURNISSEUR", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDER")]
        public EntityCollection<COMMANDER> COMMANDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMMANDER>("DADModel.FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMMANDER>("DADModel.FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="COMMANDER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COMMANDER : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet COMMANDER.
        /// </summary>
        /// <param name="id_commande_fournisseur">Valeur initiale de la propriété id_commande_fournisseur.</param>
        /// <param name="id_produit">Valeur initiale de la propriété id_produit.</param>
        /// <param name="quantite">Valeur initiale de la propriété quantite.</param>
        public static COMMANDER CreateCOMMANDER(global::System.Guid id_commande_fournisseur, global::System.Guid id_produit, global::System.Decimal quantite)
        {
            COMMANDER cOMMANDER = new COMMANDER();
            cOMMANDER.id_commande_fournisseur = id_commande_fournisseur;
            cOMMANDER.id_produit = id_produit;
            cOMMANDER.quantite = quantite;
            return cOMMANDER;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_commande_fournisseur
        {
            get
            {
                return _id_commande_fournisseur;
            }
            set
            {
                if (_id_commande_fournisseur != value)
                {
                    Onid_commande_fournisseurChanging(value);
                    ReportPropertyChanging("id_commande_fournisseur");
                    _id_commande_fournisseur = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_commande_fournisseur");
                    Onid_commande_fournisseurChanged();
                }
            }
        }
        private global::System.Guid _id_commande_fournisseur;
        partial void Onid_commande_fournisseurChanging(global::System.Guid value);
        partial void Onid_commande_fournisseurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_produit
        {
            get
            {
                return _id_produit;
            }
            set
            {
                if (_id_produit != value)
                {
                    Onid_produitChanging(value);
                    ReportPropertyChanging("id_produit");
                    _id_produit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_produit");
                    Onid_produitChanged();
                }
            }
        }
        private global::System.Guid _id_produit;
        partial void Onid_produitChanging(global::System.Guid value);
        partial void Onid_produitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal quantite
        {
            get
            {
                return _quantite;
            }
            set
            {
                OnquantiteChanging(value);
                ReportPropertyChanging("quantite");
                _quantite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantite");
                OnquantiteChanged();
            }
        }
        private global::System.Decimal _quantite;
        partial void OnquantiteChanging(global::System.Decimal value);
        partial void OnquantiteChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDE_FOURNISSEUR")]
        public COMMANDE_FOURNISSEUR COMMANDE_FOURNISSEUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDE_FOURNISSEUR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDE_FOURNISSEUR").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<COMMANDE_FOURNISSEUR> COMMANDE_FOURNISSEURReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDE_FOURNISSEUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDER_COMMANDE_FOURNISSEUR", "COMMANDE_FOURNISSEUR", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDER_PRODUIT", "PRODUIT")]
        public PRODUIT PRODUIT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUIT>("DADModel.FK_COMMANDER_PRODUIT", "PRODUIT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUIT>("DADModel.FK_COMMANDER_PRODUIT", "PRODUIT").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUIT> PRODUITReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUIT>("DADModel.FK_COMMANDER_PRODUIT", "PRODUIT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUIT>("DADModel.FK_COMMANDER_PRODUIT", "PRODUIT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="FOURNISSEUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FOURNISSEUR : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet FOURNISSEUR.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="email">Valeur initiale de la propriété email.</param>
        /// <param name="phone">Valeur initiale de la propriété phone.</param>
        /// <param name="password">Valeur initiale de la propriété password.</param>
        /// <param name="adresse">Valeur initiale de la propriété adresse.</param>
        /// <param name="ville">Valeur initiale de la propriété ville.</param>
        /// <param name="code_postal">Valeur initiale de la propriété code_postal.</param>
        public static FOURNISSEUR CreateFOURNISSEUR(global::System.Guid id, global::System.String nom, global::System.String email, global::System.String phone, global::System.String password, global::System.String adresse, global::System.String ville, global::System.String code_postal)
        {
            FOURNISSEUR fOURNISSEUR = new FOURNISSEUR();
            fOURNISSEUR.id = id;
            fOURNISSEUR.nom = nom;
            fOURNISSEUR.email = email;
            fOURNISSEUR.phone = phone;
            fOURNISSEUR.password = password;
            fOURNISSEUR.adresse = adresse;
            fOURNISSEUR.ville = ville;
            fOURNISSEUR.code_postal = code_postal;
            return fOURNISSEUR;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ville
        {
            get
            {
                return _ville;
            }
            set
            {
                OnvilleChanging(value);
                ReportPropertyChanging("ville");
                _ville = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ville");
                OnvilleChanged();
            }
        }
        private global::System.String _ville;
        partial void OnvilleChanging(global::System.String value);
        partial void OnvilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String code_postal
        {
            get
            {
                return _code_postal;
            }
            set
            {
                Oncode_postalChanging(value);
                ReportPropertyChanging("code_postal");
                _code_postal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("code_postal");
                Oncode_postalChanged();
            }
        }
        private global::System.String _code_postal;
        partial void Oncode_postalChanging(global::System.String value);
        partial void Oncode_postalChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "COMMANDE_FOURNISSEUR")]
        public EntityCollection<COMMANDE_FOURNISSEUR> COMMANDE_FOURNISSEUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "COMMANDE_FOURNISSEUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMMANDE_FOURNISSEUR>("DADModel.FK_COMMANDE_FOURNISSEUR_FOURNISSEUR", "COMMANDE_FOURNISSEUR", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DADModel", Name="PRODUIT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUIT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet PRODUIT.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="reference">Valeur initiale de la propriété reference.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="marque">Valeur initiale de la propriété marque.</param>
        /// <param name="id_fournisseur">Valeur initiale de la propriété id_fournisseur.</param>
        /// <param name="prix">Valeur initiale de la propriété prix.</param>
        /// <param name="stock">Valeur initiale de la propriété stock.</param>
        public static PRODUIT CreatePRODUIT(global::System.Guid id, global::System.String reference, global::System.String nom, global::System.String marque, global::System.Guid id_fournisseur, global::System.Decimal prix, global::System.Decimal stock)
        {
            PRODUIT pRODUIT = new PRODUIT();
            pRODUIT.id = id;
            pRODUIT.reference = reference;
            pRODUIT.nom = nom;
            pRODUIT.marque = marque;
            pRODUIT.id_fournisseur = id_fournisseur;
            pRODUIT.prix = prix;
            pRODUIT.stock = stock;
            return pRODUIT;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String reference
        {
            get
            {
                return _reference;
            }
            set
            {
                OnreferenceChanging(value);
                ReportPropertyChanging("reference");
                _reference = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("reference");
                OnreferenceChanged();
            }
        }
        private global::System.String _reference;
        partial void OnreferenceChanging(global::System.String value);
        partial void OnreferenceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String marque
        {
            get
            {
                return _marque;
            }
            set
            {
                OnmarqueChanging(value);
                ReportPropertyChanging("marque");
                _marque = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("marque");
                OnmarqueChanged();
            }
        }
        private global::System.String _marque;
        partial void OnmarqueChanging(global::System.String value);
        partial void OnmarqueChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_fournisseur
        {
            get
            {
                return _id_fournisseur;
            }
            set
            {
                Onid_fournisseurChanging(value);
                ReportPropertyChanging("id_fournisseur");
                _id_fournisseur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_fournisseur");
                Onid_fournisseurChanged();
            }
        }
        private global::System.Guid _id_fournisseur;
        partial void Onid_fournisseurChanging(global::System.Guid value);
        partial void Onid_fournisseurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prix
        {
            get
            {
                return _prix;
            }
            set
            {
                OnprixChanging(value);
                ReportPropertyChanging("prix");
                _prix = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prix");
                OnprixChanged();
            }
        }
        private global::System.Decimal _prix;
        partial void OnprixChanging(global::System.Decimal value);
        partial void OnprixChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal stock
        {
            get
            {
                return _stock;
            }
            set
            {
                OnstockChanging(value);
                ReportPropertyChanging("stock");
                _stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stock");
                OnstockChanged();
            }
        }
        private global::System.Decimal _stock;
        partial void OnstockChanging(global::System.Decimal value);
        partial void OnstockChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "FK_COMMANDER_PRODUIT", "COMMANDER")]
        public EntityCollection<COMMANDER> COMMANDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMMANDER>("DADModel.FK_COMMANDER_PRODUIT", "COMMANDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMMANDER>("DADModel.FK_COMMANDER_PRODUIT", "COMMANDER", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DADModel", "APPARTIENT", "CATEGORIE")]
        public EntityCollection<CATEGORIE> CATEGORIE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CATEGORIE>("DADModel.APPARTIENT", "CATEGORIE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CATEGORIE>("DADModel.APPARTIENT", "CATEGORIE", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
