//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowServices.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemState", Namespace="http://schemas.datacontract.org/2004/07/SessionService")]
    public enum ItemState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAVAILABLE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOW = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INSUFFICIENT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_VERIFIED = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatState", Namespace="http://schemas.datacontract.org/2004/07/SessionService")]
    public enum ChatState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MESSAGED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLOSED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISCONNECTED = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/SessionService")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADMINISTRATOR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOURNISSEUR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOW = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartEntrie", Namespace="http://schemas.datacontract.org/2004/07/SessionService")]
    [System.SerializableAttribute()]
    public partial class CartEntrie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((this.ObjectIDField.Equals(value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Customer", CallbackContract=typeof(WorkflowServices.Service.CustomerCallback))]
    public interface Customer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Customer/DisconnectClient", ReplyAction="http://tempuri.org/Customer/DisconnectClientResponse")]
        WorkflowServices.Service.DisconnectClientResponse DisconnectClient(WorkflowServices.Service.DisconnectClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Customer/ActivateClient", ReplyAction="http://tempuri.org/Customer/ActivateClientResponse")]
        WorkflowServices.Service.ActivateClientResponse ActivateClient(WorkflowServices.Service.ActivateClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Customer/AddItemInCart", ReplyAction="http://tempuri.org/Customer/AddItemInCartResponse")]
        WorkflowServices.Service.AddItemInCartResponse AddItemInCart(WorkflowServices.Service.AddItemInCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Customer/RemoveItemInCart", ReplyAction="http://tempuri.org/Customer/RemoveItemInCartResponse")]
        WorkflowServices.Service.RemoveItemInCartResponse RemoveItemInCart(WorkflowServices.Service.RemoveItemInCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Customer/RemoveCartContentClient", ReplyAction="http://tempuri.org/Customer/RemoveCartContentClientResponse")]
        WorkflowServices.Service.RemoveCartContentClientResponse RemoveCartContentClient(WorkflowServices.Service.RemoveCartContentClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Customer/ChatUpdateClient", ReplyAction="http://tempuri.org/Customer/ChatUpdateClientResponse")]
        WorkflowServices.Service.ChatUpdateClientResponse ChatUpdateClient(WorkflowServices.Service.ChatUpdateClientRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Customer/CartNotification")]
        void CartNotification(WorkflowServices.Service.CartNotification request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Customer/OrderNotification")]
        void OrderNotification(WorkflowServices.Service.OrderNotification request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Customer/DisconnectedClient")]
        void DisconnectedClient(WorkflowServices.Service.DisconnectedClient request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Customer/ChatNotificationClient")]
        void ChatNotificationClient(WorkflowServices.Service.ChatNotificationClient request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public DisconnectClientRequest() {
        }
        
        public DisconnectClientRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DisconnectClientResult;
        
        public DisconnectClientResponse() {
        }
        
        public DisconnectClientResponse(bool DisconnectClientResult) {
            this.DisconnectClientResult = DisconnectClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActivateClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid userID;
        
        public ActivateClientRequest() {
        }
        
        public ActivateClientRequest(System.Guid sessionID, System.Guid userID) {
            this.sessionID = sessionID;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActivateClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ActivateClientResult;
        
        public ActivateClientResponse() {
        }
        
        public ActivateClientResponse(bool ActivateClientResult) {
            this.ActivateClientResult = ActivateClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddItemInCart", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddItemInCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid itemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int quantitie;
        
        public AddItemInCartRequest() {
        }
        
        public AddItemInCartRequest(System.Guid sessionID, System.Guid itemID, int quantitie) {
            this.sessionID = sessionID;
            this.itemID = itemID;
            this.quantitie = quantitie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddItemInCartResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddItemInCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WorkflowServices.Service.ItemState AddItemInCartResult;
        
        public AddItemInCartResponse() {
        }
        
        public AddItemInCartResponse(WorkflowServices.Service.ItemState AddItemInCartResult) {
            this.AddItemInCartResult = AddItemInCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveItemInCart", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveItemInCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid itemID;
        
        public RemoveItemInCartRequest() {
        }
        
        public RemoveItemInCartRequest(System.Guid sessionID, System.Guid itemID) {
            this.sessionID = sessionID;
            this.itemID = itemID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveItemInCartResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveItemInCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RemoveItemInCartResult;
        
        public RemoveItemInCartResponse() {
        }
        
        public RemoveItemInCartResponse(bool RemoveItemInCartResult) {
            this.RemoveItemInCartResult = RemoveItemInCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCartContentClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCartContentClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public RemoveCartContentClientRequest() {
        }
        
        public RemoveCartContentClientRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCartContentClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCartContentClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RemoveCartContentClientResult;
        
        public RemoveCartContentClientResponse() {
        }
        
        public RemoveCartContentClientResponse(bool RemoveCartContentClientResult) {
            this.RemoveCartContentClientResult = RemoveCartContentClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatUpdateClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatUpdateClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid correspondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WorkflowServices.Service.ChatState state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string message;
        
        public ChatUpdateClientRequest() {
        }
        
        public ChatUpdateClientRequest(System.Guid sessionID, System.Guid correspondentID, WorkflowServices.Service.ChatState state, string message) {
            this.sessionID = sessionID;
            this.correspondentID = correspondentID;
            this.state = state;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatUpdateClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatUpdateClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ChatUpdateClientResult;
        
        public ChatUpdateClientResponse() {
        }
        
        public ChatUpdateClientResponse(bool ChatUpdateClientResult) {
            this.ChatUpdateClientResult = ChatUpdateClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CartNotification", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CartNotification {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid itemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int newQuantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WorkflowServices.Service.ItemState state;
        
        public CartNotification() {
        }
        
        public CartNotification(System.Guid itemID, int newQuantity, WorkflowServices.Service.ItemState state) {
            this.itemID = itemID;
            this.newQuantity = newQuantity;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderNotification", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderNotification {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid orderID;
        
        public OrderNotification() {
        }
        
        public OrderNotification(System.Guid orderID) {
            this.orderID = orderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectedClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectedClient {
        
        public DisconnectedClient() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatNotificationClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatNotificationClient {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid correspondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WorkflowServices.Service.ChatState state;
        
        public ChatNotificationClient() {
        }
        
        public ChatNotificationClient(System.Guid correspondentID, string message, WorkflowServices.Service.ChatState state) {
            this.correspondentID = correspondentID;
            this.message = message;
            this.state = state;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Administrator", CallbackContract=typeof(WorkflowServices.Service.AdministratorCallback))]
    public interface Administrator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Administrator/DisconnectAdministrateur", ReplyAction="http://tempuri.org/Administrator/DisconnectAdministrateurResponse")]
        WorkflowServices.Service.DisconnectAdministrateurResponse DisconnectAdministrateur(WorkflowServices.Service.DisconnectAdministrateurRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Administrator/Connect", ReplyAction="http://tempuri.org/Administrator/ConnectResponse")]
        WorkflowServices.Service.ConnectResponse Connect(WorkflowServices.Service.ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Administrator/ChatUpdateAdministrator", ReplyAction="http://tempuri.org/Administrator/ChatUpdateAdministratorResponse")]
        WorkflowServices.Service.ChatUpdateAdministratorResponse ChatUpdateAdministrator(WorkflowServices.Service.ChatUpdateAdministratorRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdministratorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Administrator/CategorieAdded")]
        void CategorieAdded(WorkflowServices.Service.CategorieAdded request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Administrator/DisconnectedAdministrator")]
        void DisconnectedAdministrator(WorkflowServices.Service.DisconnectedAdministrator request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Administrator/ChatNotificationAdministrator")]
        void ChatNotificationAdministrator(WorkflowServices.Service.ChatNotificationAdministrator request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectAdministrateur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectAdministrateurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public DisconnectAdministrateurRequest() {
        }
        
        public DisconnectAdministrateurRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectAdministrateurResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectAdministrateurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DisconnectAdministrateurResult;
        
        public DisconnectAdministrateurResponse() {
        }
        
        public DisconnectAdministrateurResponse(bool DisconnectAdministrateurResult) {
            this.DisconnectAdministrateurResult = DisconnectAdministrateurResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Connect", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConnectRequest {
        
        public ConnectRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConnectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConnectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid ConnectResult;
        
        public ConnectResponse() {
        }
        
        public ConnectResponse(System.Guid ConnectResult) {
            this.ConnectResult = ConnectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatUpdateAdministrator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatUpdateAdministratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid correspondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WorkflowServices.Service.ChatState state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string message;
        
        public ChatUpdateAdministratorRequest() {
        }
        
        public ChatUpdateAdministratorRequest(System.Guid sessionID, System.Guid correspondentID, WorkflowServices.Service.ChatState state, string message) {
            this.sessionID = sessionID;
            this.correspondentID = correspondentID;
            this.state = state;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatUpdateAdministratorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatUpdateAdministratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ChatUpdateAdministratorResult;
        
        public ChatUpdateAdministratorResponse() {
        }
        
        public ChatUpdateAdministratorResponse(bool ChatUpdateAdministratorResult) {
            this.ChatUpdateAdministratorResult = ChatUpdateAdministratorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CategorieAdded", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CategorieAdded {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid categorieID;
        
        public CategorieAdded() {
        }
        
        public CategorieAdded(System.Guid categorieID) {
            this.categorieID = categorieID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectedAdministrator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectedAdministrator {
        
        public DisconnectedAdministrator() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatNotificationAdministrator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatNotificationAdministrator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid correspondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WorkflowServices.Service.ChatState state;
        
        public ChatNotificationAdministrator() {
        }
        
        public ChatNotificationAdministrator(System.Guid correspondentID, string message, WorkflowServices.Service.ChatState state) {
            this.correspondentID = correspondentID;
            this.message = message;
            this.state = state;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Fournisseur", CallbackContract=typeof(WorkflowServices.Service.FournisseurCallback))]
    public interface Fournisseur {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fournisseur/DisconnectFournisseur", ReplyAction="http://tempuri.org/Fournisseur/DisconnectFournisseurResponse")]
        WorkflowServices.Service.DisconnectFournisseurResponse DisconnectFournisseur(WorkflowServices.Service.DisconnectFournisseurRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fournisseur/ActivateFournisseur", ReplyAction="http://tempuri.org/Fournisseur/ActivateFournisseurResponse")]
        WorkflowServices.Service.ActivateFournisseurResponse ActivateFournisseur(WorkflowServices.Service.ActivateFournisseurRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fournisseur/ChatUpdateFournisseur", ReplyAction="http://tempuri.org/Fournisseur/ChatUpdateFournisseurResponse")]
        WorkflowServices.Service.ChatUpdateFournisseurResponse ChatUpdateFournisseur(WorkflowServices.Service.ChatUpdateFournisseurRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FournisseurCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Fournisseur/NewOrder")]
        void NewOrder(WorkflowServices.Service.NewOrder request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Fournisseur/CategorieNotification")]
        void CategorieNotification(WorkflowServices.Service.CategorieNotification request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Fournisseur/ProductNotification")]
        void ProductNotification(WorkflowServices.Service.ProductNotification request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Fournisseur/ChatNotificationFournisseur")]
        void ChatNotificationFournisseur(WorkflowServices.Service.ChatNotificationFournisseur request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Fournisseur/DisconnectedFournisseur")]
        void DisconnectedFournisseur(WorkflowServices.Service.DisconnectedFournisseur request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectFournisseur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectFournisseurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public DisconnectFournisseurRequest() {
        }
        
        public DisconnectFournisseurRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectFournisseurResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectFournisseurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DisconnectFournisseurResult;
        
        public DisconnectFournisseurResponse() {
        }
        
        public DisconnectFournisseurResponse(bool DisconnectFournisseurResult) {
            this.DisconnectFournisseurResult = DisconnectFournisseurResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateFournisseur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActivateFournisseurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid userID;
        
        public ActivateFournisseurRequest() {
        }
        
        public ActivateFournisseurRequest(System.Guid sessionID, System.Guid userID) {
            this.sessionID = sessionID;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateFournisseurResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActivateFournisseurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ActivateFournisseurResult;
        
        public ActivateFournisseurResponse() {
        }
        
        public ActivateFournisseurResponse(bool ActivateFournisseurResult) {
            this.ActivateFournisseurResult = ActivateFournisseurResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatUpdateFournisseur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatUpdateFournisseurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid correspondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WorkflowServices.Service.ChatState state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string message;
        
        public ChatUpdateFournisseurRequest() {
        }
        
        public ChatUpdateFournisseurRequest(System.Guid sessionID, System.Guid correspondentID, WorkflowServices.Service.ChatState state, string message) {
            this.sessionID = sessionID;
            this.correspondentID = correspondentID;
            this.state = state;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatUpdateFournisseurResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatUpdateFournisseurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ChatUpdateFournisseurResult;
        
        public ChatUpdateFournisseurResponse() {
        }
        
        public ChatUpdateFournisseurResponse(bool ChatUpdateFournisseurResult) {
            this.ChatUpdateFournisseurResult = ChatUpdateFournisseurResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid orderID;
        
        public NewOrder() {
        }
        
        public NewOrder(System.Guid orderID) {
            this.orderID = orderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CategorieNotification", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CategorieNotification {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid categorieID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool deleted;
        
        public CategorieNotification() {
        }
        
        public CategorieNotification(System.Guid categorieID, bool deleted) {
            this.categorieID = categorieID;
            this.deleted = deleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductNotification", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProductNotification {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid itemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool deleted;
        
        public ProductNotification() {
        }
        
        public ProductNotification(System.Guid itemID, bool deleted) {
            this.itemID = itemID;
            this.deleted = deleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChatNotificationFournisseur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChatNotificationFournisseur {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid correspondentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WorkflowServices.Service.ChatState state;
        
        public ChatNotificationFournisseur() {
        }
        
        public ChatNotificationFournisseur(System.Guid correspondentID, string message, WorkflowServices.Service.ChatState state) {
            this.correspondentID = correspondentID;
            this.message = message;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectedFournisseur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisconnectedFournisseur {
        
        public DisconnectedFournisseur() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Workflow")]
    public interface Workflow {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Workflow/CreateSession", ReplyAction="http://tempuri.org/Workflow/CreateSessionResponse")]
        WorkflowServices.Service.CreateSessionResponse CreateSession(WorkflowServices.Service.CreateSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Workflow/GetCart", ReplyAction="http://tempuri.org/Workflow/GetCartResponse")]
        WorkflowServices.Service.GetCartResponse GetCart(WorkflowServices.Service.GetCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Workflow/GetUserID", ReplyAction="http://tempuri.org/Workflow/GetUserIDResponse")]
        WorkflowServices.Service.GetUserIDResponse GetUserID(WorkflowServices.Service.GetUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Workflow/GetSessionType", ReplyAction="http://tempuri.org/Workflow/GetSessionTypeResponse")]
        WorkflowServices.Service.GetSessionTypeResponse GetSessionType(WorkflowServices.Service.GetSessionTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Workflow/ChangeItemAvailability", ReplyAction="http://tempuri.org/Workflow/ChangeItemAvailabilityResponse")]
        WorkflowServices.Service.ChangeItemAvailabilityResponse ChangeItemAvailability(WorkflowServices.Service.ChangeItemAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Workflow/AdminProductModification", ReplyAction="http://tempuri.org/Workflow/AdminProductModificationResponse")]
        WorkflowServices.Service.AdminProductModificationResponse AdminProductModification(WorkflowServices.Service.AdminProductModificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Workflow/RemoveCartContent", ReplyAction="http://tempuri.org/Workflow/RemoveCartContentResponse")]
        WorkflowServices.Service.RemoveCartContentResponse RemoveCartContent(WorkflowServices.Service.RemoveCartContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSession", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WorkflowServices.Service.UserType type;
        
        public CreateSessionRequest() {
        }
        
        public CreateSessionRequest(System.Guid userID, WorkflowServices.Service.UserType type) {
            this.userID = userID;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSessionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid CreateSessionResult;
        
        public CreateSessionResponse() {
        }
        
        public CreateSessionResponse(System.Guid CreateSessionResult) {
            this.CreateSessionResult = CreateSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCart", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public GetCartRequest() {
        }
        
        public GetCartRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCartResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WorkflowServices.Service.CartEntrie[] GetCartResult;
        
        public GetCartResponse() {
        }
        
        public GetCartResponse(WorkflowServices.Service.CartEntrie[] GetCartResult) {
            this.GetCartResult = GetCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public GetUserIDRequest() {
        }
        
        public GetUserIDRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid GetUserIDResult;
        
        public GetUserIDResponse() {
        }
        
        public GetUserIDResponse(System.Guid GetUserIDResult) {
            this.GetUserIDResult = GetUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSessionType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSessionTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public GetSessionTypeRequest() {
        }
        
        public GetSessionTypeRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSessionTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSessionTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WorkflowServices.Service.UserType GetSessionTypeResult;
        
        public GetSessionTypeResponse() {
        }
        
        public GetSessionTypeResponse(WorkflowServices.Service.UserType GetSessionTypeResult) {
            this.GetSessionTypeResult = GetSessionTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeItemAvailability", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeItemAvailabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid itemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int quantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool available;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool exist;
        
        public ChangeItemAvailabilityRequest() {
        }
        
        public ChangeItemAvailabilityRequest(System.Guid itemID, int quantity, bool available, bool exist) {
            this.itemID = itemID;
            this.quantity = quantity;
            this.available = available;
            this.exist = exist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeItemAvailabilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeItemAvailabilityResponse {
        
        public ChangeItemAvailabilityResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdminProductModification", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdminProductModificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid itemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid fournisseurID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool deleted;
        
        public AdminProductModificationRequest() {
        }
        
        public AdminProductModificationRequest(System.Guid itemID, System.Guid fournisseurID, bool deleted) {
            this.itemID = itemID;
            this.fournisseurID = fournisseurID;
            this.deleted = deleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdminProductModificationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdminProductModificationResponse {
        
        public AdminProductModificationResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCartContent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCartContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid sessionID;
        
        public RemoveCartContentRequest() {
        }
        
        public RemoveCartContentRequest(System.Guid sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCartContentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCartContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RemoveCartContentResult;
        
        public RemoveCartContentResponse() {
        }
        
        public RemoveCartContentResponse(bool RemoveCartContentResult) {
            this.RemoveCartContentResult = RemoveCartContentResult;
        }
    }
}
