//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FournisseurTest.WorkflowConnection {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkflowConnection.IService")]
    public interface IService {
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetUserIdentifier n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserIdentifier", ReplyAction="http://tempuri.org/IService/GetUserIdentifierResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FournisseurTest.WorkflowConnection.GetUserIdentifierResponse1 GetUserIdentifier(FournisseurTest.WorkflowConnection.GetUserIdentifierRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetUserPassword n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserPassword", ReplyAction="http://tempuri.org/IService/GetUserPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FournisseurTest.WorkflowConnection.GetUserPasswordResponse1 GetUserPassword(FournisseurTest.WorkflowConnection.GetUserPasswordRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GuidRequest n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GuidRequest", ReplyAction="http://tempuri.org/IService/GuidRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FournisseurTest.WorkflowConnection.GuidRequestResponse GuidRequest(FournisseurTest.WorkflowConnection.GuidRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetUserIdentifierResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CheckIfFournisseurExistResult userExistField;
        
        private bool userExistFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CheckIfFournisseurExistResult UserExist {
            get {
                return this.userExistField;
            }
            set {
                this.userExistField = value;
                this.RaisePropertyChanged("UserExist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserExistSpecified {
            get {
                return this.userExistFieldSpecified;
            }
            set {
                this.userExistFieldSpecified = value;
                this.RaisePropertyChanged("UserExistSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WorkflowServices")]
    public enum CheckIfFournisseurExistResult {
        
        /// <remarks/>
        SERVICE_ERROR,
        
        /// <remarks/>
        DATA_ERROR,
        
        /// <remarks/>
        EXIST,
        
        /// <remarks/>
        NOT_EXIST,
        
        /// <remarks/>
        NOT_TESTED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdentifierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetUserIdentifierRequest() {
        }
        
        public GetUserIdentifierRequest(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdentifierResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FournisseurTest.WorkflowConnection.GetUserIdentifierResponse GetUserIdentifierResponse;
        
        public GetUserIdentifierResponse1() {
        }
        
        public GetUserIdentifierResponse1(FournisseurTest.WorkflowConnection.GetUserIdentifierResponse GetUserIdentifierResponse) {
            this.GetUserIdentifierResponse = GetUserIdentifierResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetUserPasswordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CheckIfPasswordMatchResult passwordMatchField;
        
        private bool passwordMatchFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CheckIfPasswordMatchResult PasswordMatch {
            get {
                return this.passwordMatchField;
            }
            set {
                this.passwordMatchField = value;
                this.RaisePropertyChanged("PasswordMatch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PasswordMatchSpecified {
            get {
                return this.passwordMatchFieldSpecified;
            }
            set {
                this.passwordMatchFieldSpecified = value;
                this.RaisePropertyChanged("PasswordMatchSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WorkflowServices")]
    public enum CheckIfPasswordMatchResult {
        
        /// <remarks/>
        SERVICE_ERROR,
        
        /// <remarks/>
        DATA_ERROR,
        
        /// <remarks/>
        MATCH,
        
        /// <remarks/>
        NOT_MATCH,
        
        /// <remarks/>
        NOT_TESTED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetUserPasswordRequest() {
        }
        
        public GetUserPasswordRequest(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPasswordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FournisseurTest.WorkflowConnection.GetUserPasswordResponse GetUserPasswordResponse;
        
        public GetUserPasswordResponse1() {
        }
        
        public GetUserPasswordResponse1(FournisseurTest.WorkflowConnection.GetUserPasswordResponse GetUserPasswordResponse) {
            this.GetUserPasswordResponse = GetUserPasswordResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuidRequestRequest {
        
        public GuidRequestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuidRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuidRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionID;
        
        public GuidRequestResponse() {
        }
        
        public GuidRequestResponse(string UserID, string SessionID) {
            this.UserID = UserID;
            this.SessionID = SessionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : FournisseurTest.WorkflowConnection.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<FournisseurTest.WorkflowConnection.IService>, FournisseurTest.WorkflowConnection.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FournisseurTest.WorkflowConnection.GetUserIdentifierResponse1 FournisseurTest.WorkflowConnection.IService.GetUserIdentifier(FournisseurTest.WorkflowConnection.GetUserIdentifierRequest request) {
            return base.Channel.GetUserIdentifier(request);
        }
        
        public FournisseurTest.WorkflowConnection.GetUserIdentifierResponse GetUserIdentifier(string @string) {
            FournisseurTest.WorkflowConnection.GetUserIdentifierRequest inValue = new FournisseurTest.WorkflowConnection.GetUserIdentifierRequest();
            inValue.@string = @string;
            FournisseurTest.WorkflowConnection.GetUserIdentifierResponse1 retVal = ((FournisseurTest.WorkflowConnection.IService)(this)).GetUserIdentifier(inValue);
            return retVal.GetUserIdentifierResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FournisseurTest.WorkflowConnection.GetUserPasswordResponse1 FournisseurTest.WorkflowConnection.IService.GetUserPassword(FournisseurTest.WorkflowConnection.GetUserPasswordRequest request) {
            return base.Channel.GetUserPassword(request);
        }
        
        public FournisseurTest.WorkflowConnection.GetUserPasswordResponse GetUserPassword(string @string) {
            FournisseurTest.WorkflowConnection.GetUserPasswordRequest inValue = new FournisseurTest.WorkflowConnection.GetUserPasswordRequest();
            inValue.@string = @string;
            FournisseurTest.WorkflowConnection.GetUserPasswordResponse1 retVal = ((FournisseurTest.WorkflowConnection.IService)(this)).GetUserPassword(inValue);
            return retVal.GetUserPasswordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FournisseurTest.WorkflowConnection.GuidRequestResponse FournisseurTest.WorkflowConnection.IService.GuidRequest(FournisseurTest.WorkflowConnection.GuidRequestRequest request) {
            return base.Channel.GuidRequest(request);
        }
        
        public string GuidRequest(out string SessionID) {
            FournisseurTest.WorkflowConnection.GuidRequestRequest inValue = new FournisseurTest.WorkflowConnection.GuidRequestRequest();
            FournisseurTest.WorkflowConnection.GuidRequestResponse retVal = ((FournisseurTest.WorkflowConnection.IService)(this)).GuidRequest(inValue);
            SessionID = retVal.SessionID;
            return retVal.UserID;
        }
    }
}
