//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceMagasin.FournisseurCreation {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckIfFournisseurExistResult", Namespace="http://schemas.datacontract.org/2004/07/WorkflowServices")]
    public enum CheckIfFournisseurExistResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICE_ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATA_ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXIST = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_EXIST = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_TESTED = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FournisseurCreation.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SessionIDVerification", ReplyAction="http://tempuri.org/IService/SessionIDVerificationResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        bool SessionIDVerification(System.Guid SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateFournisseur", ReplyAction="http://tempuri.org/IService/CreateFournisseurResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="FournisseurExist")]
        InterfaceMagasin.FournisseurCreation.CheckIfFournisseurExistResult CreateFournisseur(string Nom, string Email, string Password, string Adresse, string Ville, string Phone, string CodePostal, string Pays);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GuidRequest n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GuidRequest", ReplyAction="http://tempuri.org/IService/GuidRequestResponse")]
        InterfaceMagasin.FournisseurCreation.GuidRequestResponse GuidRequest(InterfaceMagasin.FournisseurCreation.GuidRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuidRequestRequest {
        
        public GuidRequestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuidRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public GuidRequestResponse() {
        }
        
        public GuidRequestResponse(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : InterfaceMagasin.FournisseurCreation.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<InterfaceMagasin.FournisseurCreation.IService>, InterfaceMagasin.FournisseurCreation.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SessionIDVerification(System.Guid SessionID) {
            return base.Channel.SessionIDVerification(SessionID);
        }
        
        public InterfaceMagasin.FournisseurCreation.CheckIfFournisseurExistResult CreateFournisseur(string Nom, string Email, string Password, string Adresse, string Ville, string Phone, string CodePostal, string Pays) {
            return base.Channel.CreateFournisseur(Nom, Email, Password, Adresse, Ville, Phone, CodePostal, Pays);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfaceMagasin.FournisseurCreation.GuidRequestResponse InterfaceMagasin.FournisseurCreation.IService.GuidRequest(InterfaceMagasin.FournisseurCreation.GuidRequestRequest request) {
            return base.Channel.GuidRequest(request);
        }
        
        public System.Nullable<System.Guid> GuidRequest() {
            InterfaceMagasin.FournisseurCreation.GuidRequestRequest inValue = new InterfaceMagasin.FournisseurCreation.GuidRequestRequest();
            InterfaceMagasin.FournisseurCreation.GuidRequestResponse retVal = ((InterfaceMagasin.FournisseurCreation.IService)(this)).GuidRequest(inValue);
            return retVal.guid;
        }
    }
}
