//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// Nom du fichier d'origine :
// Date de génération : 23/03/2011 16:09:04
namespace InterfaceMagasin.DataService
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour DADEntities dans le schéma.
    /// </summary>
    public partial class DADEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisez un nouvel objet DADEntities.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DADEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("DADModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("InterfaceMagasin.DataService", typeName.Substring(8)), false);
            }
            return null;
        }
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("InterfaceMagasin.DataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("DADModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour ADRESSE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ADRESSE_CLIENT> ADRESSE_CLIENT
        {
            get
            {
                if ((this._ADRESSE_CLIENT == null))
                {
                    this._ADRESSE_CLIENT = base.CreateQuery<ADRESSE_CLIENT>("ADRESSE_CLIENT");
                }
                return this._ADRESSE_CLIENT;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ADRESSE_CLIENT> _ADRESSE_CLIENT;
        /// <summary>
        /// Il n'existe aucun commentaire pour CATEGORIE dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CATEGORIE> CATEGORIE
        {
            get
            {
                if ((this._CATEGORIE == null))
                {
                    this._CATEGORIE = base.CreateQuery<CATEGORIE>("CATEGORIE");
                }
                return this._CATEGORIE;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CATEGORIE> _CATEGORIE;
        /// <summary>
        /// Il n'existe aucun commentaire pour CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CLIENT> CLIENT
        {
            get
            {
                if ((this._CLIENT == null))
                {
                    this._CLIENT = base.CreateQuery<CLIENT>("CLIENT");
                }
                return this._CLIENT;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CLIENT> _CLIENT;
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<COMMANDE_CLIENT> COMMANDE_CLIENT
        {
            get
            {
                if ((this._COMMANDE_CLIENT == null))
                {
                    this._COMMANDE_CLIENT = base.CreateQuery<COMMANDE_CLIENT>("COMMANDE_CLIENT");
                }
                return this._COMMANDE_CLIENT;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<COMMANDE_CLIENT> _COMMANDE_CLIENT;
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<COMMANDE_FOURNISSEUR> COMMANDE_FOURNISSEUR
        {
            get
            {
                if ((this._COMMANDE_FOURNISSEUR == null))
                {
                    this._COMMANDE_FOURNISSEUR = base.CreateQuery<COMMANDE_FOURNISSEUR>("COMMANDE_FOURNISSEUR");
                }
                return this._COMMANDE_FOURNISSEUR;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<COMMANDE_FOURNISSEUR> _COMMANDE_FOURNISSEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDER dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<COMMANDER> COMMANDER
        {
            get
            {
                if ((this._COMMANDER == null))
                {
                    this._COMMANDER = base.CreateQuery<COMMANDER>("COMMANDER");
                }
                return this._COMMANDER;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<COMMANDER> _COMMANDER;
        /// <summary>
        /// Il n'existe aucun commentaire pour FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FOURNISSEUR> FOURNISSEUR
        {
            get
            {
                if ((this._FOURNISSEUR == null))
                {
                    this._FOURNISSEUR = base.CreateQuery<FOURNISSEUR>("FOURNISSEUR");
                }
                return this._FOURNISSEUR;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FOURNISSEUR> _FOURNISSEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour IMAGE dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<IMAGE> IMAGE
        {
            get
            {
                if ((this._IMAGE == null))
                {
                    this._IMAGE = base.CreateQuery<IMAGE>("IMAGE");
                }
                return this._IMAGE;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<IMAGE> _IMAGE;
        /// <summary>
        /// Il n'existe aucun commentaire pour PRODUIT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PRODUIT> PRODUIT
        {
            get
            {
                if ((this._PRODUIT == null))
                {
                    this._PRODUIT = base.CreateQuery<PRODUIT>("PRODUIT");
                }
                return this._PRODUIT;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PRODUIT> _PRODUIT;
        /// <summary>
        /// Il n'existe aucun commentaire pour ADRESSE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToADRESSE_CLIENT(ADRESSE_CLIENT aDRESSE_CLIENT)
        {
            base.AddObject("ADRESSE_CLIENT", aDRESSE_CLIENT);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour CATEGORIE dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCATEGORIE(CATEGORIE cATEGORIE)
        {
            base.AddObject("CATEGORIE", cATEGORIE);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCLIENT(CLIENT cLIENT)
        {
            base.AddObject("CLIENT", cLIENT);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCOMMANDE_CLIENT(COMMANDE_CLIENT cOMMANDE_CLIENT)
        {
            base.AddObject("COMMANDE_CLIENT", cOMMANDE_CLIENT);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCOMMANDE_FOURNISSEUR(COMMANDE_FOURNISSEUR cOMMANDE_FOURNISSEUR)
        {
            base.AddObject("COMMANDE_FOURNISSEUR", cOMMANDE_FOURNISSEUR);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDER dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCOMMANDER(COMMANDER cOMMANDER)
        {
            base.AddObject("COMMANDER", cOMMANDER);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFOURNISSEUR(FOURNISSEUR fOURNISSEUR)
        {
            base.AddObject("FOURNISSEUR", fOURNISSEUR);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour IMAGE dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToIMAGE(IMAGE iMAGE)
        {
            base.AddObject("IMAGE", iMAGE);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour PRODUIT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPRODUIT(PRODUIT pRODUIT)
        {
            base.AddObject("PRODUIT", pRODUIT);
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.ADRESSE_CLIENT dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ADRESSE_CLIENT")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class ADRESSE_CLIENT : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet ADRESSE_CLIENT.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="adresse">Valeur initiale de adresse.</param>
        /// <param name="ville">Valeur initiale de ville.</param>
        /// <param name="code_postal">Valeur initiale de code_postal.</param>
        /// <param name="pays">Valeur initiale de pays.</param>
        /// <param name="supprime">Valeur initiale de supprime.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ADRESSE_CLIENT CreateADRESSE_CLIENT(global::System.Guid ID, string adresse, string ville, string code_postal, string pays, bool supprime)
        {
            ADRESSE_CLIENT aDRESSE_CLIENT = new ADRESSE_CLIENT();
            aDRESSE_CLIENT.id = ID;
            aDRESSE_CLIENT.adresse = adresse;
            aDRESSE_CLIENT.ville = ville;
            aDRESSE_CLIENT.code_postal = code_postal;
            aDRESSE_CLIENT.pays = pays;
            aDRESSE_CLIENT.supprime = supprime;
            return aDRESSE_CLIENT;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété adresse dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string adresse
        {
            get
            {
                return this._adresse;
            }
            set
            {
                this.OnadresseChanging(value);
                this._adresse = value;
                this.OnadresseChanged();
                this.OnPropertyChanged("adresse");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _adresse;
        partial void OnadresseChanging(string value);
        partial void OnadresseChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété ville dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ville
        {
            get
            {
                return this._ville;
            }
            set
            {
                this.OnvilleChanging(value);
                this._ville = value;
                this.OnvilleChanged();
                this.OnPropertyChanged("ville");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ville;
        partial void OnvilleChanging(string value);
        partial void OnvilleChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété code_postal dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string code_postal
        {
            get
            {
                return this._code_postal;
            }
            set
            {
                this.Oncode_postalChanging(value);
                this._code_postal = value;
                this.Oncode_postalChanged();
                this.OnPropertyChanged("code_postal");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _code_postal;
        partial void Oncode_postalChanging(string value);
        partial void Oncode_postalChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété pays dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string pays
        {
            get
            {
                return this._pays;
            }
            set
            {
                this.OnpaysChanging(value);
                this._pays = value;
                this.OnpaysChanged();
                this.OnPropertyChanged("pays");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _pays;
        partial void OnpaysChanging(string value);
        partial void OnpaysChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété supprime dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool supprime
        {
            get
            {
                return this._supprime;
            }
            set
            {
                this.OnsupprimeChanging(value);
                this._supprime = value;
                this.OnsupprimeChanged();
                this.OnPropertyChanged("supprime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _supprime;
        partial void OnsupprimeChanging(bool value);
        partial void OnsupprimeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CLIENT CLIENT
        {
            get
            {
                return this._CLIENT;
            }
            set
            {
                this._CLIENT = value;
                this.OnPropertyChanged("CLIENT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CLIENT _CLIENT;
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<COMMANDE_CLIENT> COMMANDE_CLIENT
        {
            get
            {
                return this._COMMANDE_CLIENT;
            }
            set
            {
                this._COMMANDE_CLIENT = value;
                this.OnPropertyChanged("COMMANDE_CLIENT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<COMMANDE_CLIENT> _COMMANDE_CLIENT = new global::System.Data.Services.Client.DataServiceCollection<COMMANDE_CLIENT>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.CATEGORIE dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CATEGORIE")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class CATEGORIE : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet CATEGORIE.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="nom">Valeur initiale de nom.</param>
        /// <param name="valide">Valeur initiale de valide.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CATEGORIE CreateCATEGORIE(global::System.Guid ID, string nom, bool valide)
        {
            CATEGORIE cATEGORIE = new CATEGORIE();
            cATEGORIE.id = ID;
            cATEGORIE.nom = nom;
            cATEGORIE.valide = valide;
            return cATEGORIE;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nom dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                this._nom = value;
                this.OnnomChanged();
                this.OnPropertyChanged("nom");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété valide dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool valide
        {
            get
            {
                return this._valide;
            }
            set
            {
                this.OnvalideChanging(value);
                this._valide = value;
                this.OnvalideChanged();
                this.OnPropertyChanged("valide");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _valide;
        partial void OnvalideChanging(bool value);
        partial void OnvalideChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour CATEGORIE1 dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CATEGORIE> CATEGORIE1
        {
            get
            {
                return this._CATEGORIE1;
            }
            set
            {
                this._CATEGORIE1 = value;
                this.OnPropertyChanged("CATEGORIE1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CATEGORIE> _CATEGORIE1 = new global::System.Data.Services.Client.DataServiceCollection<CATEGORIE>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour CATEGORIE2 dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CATEGORIE CATEGORIE2
        {
            get
            {
                return this._CATEGORIE2;
            }
            set
            {
                this._CATEGORIE2 = value;
                this.OnPropertyChanged("CATEGORIE2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CATEGORIE _CATEGORIE2;
        /// <summary>
        /// Il n'existe aucun commentaire pour PRODUIT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PRODUIT> PRODUIT
        {
            get
            {
                return this._PRODUIT;
            }
            set
            {
                this._PRODUIT = value;
                this.OnPropertyChanged("PRODUIT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PRODUIT> _PRODUIT = new global::System.Data.Services.Client.DataServiceCollection<PRODUIT>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.CLIENT dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CLIENT")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class CLIENT : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet CLIENT.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="nom">Valeur initiale de nom.</param>
        /// <param name="prenom">Valeur initiale de prenom.</param>
        /// <param name="phone">Valeur initiale de phone.</param>
        /// <param name="email">Valeur initiale de email.</param>
        /// <param name="password">Valeur initiale de password.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CLIENT CreateCLIENT(global::System.Guid ID, string nom, string prenom, string phone, string email, string password)
        {
            CLIENT cLIENT = new CLIENT();
            cLIENT.id = ID;
            cLIENT.nom = nom;
            cLIENT.prenom = prenom;
            cLIENT.phone = phone;
            cLIENT.email = email;
            cLIENT.password = password;
            return cLIENT;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nom dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                this._nom = value;
                this.OnnomChanged();
                this.OnPropertyChanged("nom");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prenom dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prenom
        {
            get
            {
                return this._prenom;
            }
            set
            {
                this.OnprenomChanging(value);
                this._prenom = value;
                this.OnprenomChanged();
                this.OnPropertyChanged("prenom");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prenom;
        partial void OnprenomChanging(string value);
        partial void OnprenomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété phone dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string phone
        {
            get
            {
                return this._phone;
            }
            set
            {
                this.OnphoneChanging(value);
                this._phone = value;
                this.OnphoneChanged();
                this.OnPropertyChanged("phone");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _phone;
        partial void OnphoneChanging(string value);
        partial void OnphoneChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété email dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this._email = value;
                this.OnemailChanged();
                this.OnPropertyChanged("email");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété password dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                this.OnpasswordChanging(value);
                this._password = value;
                this.OnpasswordChanged();
                this.OnPropertyChanged("password");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _password;
        partial void OnpasswordChanging(string value);
        partial void OnpasswordChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour ADRESSE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ADRESSE_CLIENT> ADRESSE_CLIENT
        {
            get
            {
                return this._ADRESSE_CLIENT;
            }
            set
            {
                this._ADRESSE_CLIENT = value;
                this.OnPropertyChanged("ADRESSE_CLIENT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ADRESSE_CLIENT> _ADRESSE_CLIENT = new global::System.Data.Services.Client.DataServiceCollection<ADRESSE_CLIENT>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<COMMANDE_CLIENT> COMMANDE_CLIENT
        {
            get
            {
                return this._COMMANDE_CLIENT;
            }
            set
            {
                this._COMMANDE_CLIENT = value;
                this.OnPropertyChanged("COMMANDE_CLIENT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<COMMANDE_CLIENT> _COMMANDE_CLIENT = new global::System.Data.Services.Client.DataServiceCollection<COMMANDE_CLIENT>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.COMMANDE_CLIENT dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("COMMANDE_CLIENT")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class COMMANDE_CLIENT : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet COMMANDE_CLIENT.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="date">Valeur initiale de date.</param>
        /// <param name="prix_total">Valeur initiale de prix_total.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static COMMANDE_CLIENT CreateCOMMANDE_CLIENT(global::System.Guid ID, global::System.DateTime date, decimal prix_total)
        {
            COMMANDE_CLIENT cOMMANDE_CLIENT = new COMMANDE_CLIENT();
            cOMMANDE_CLIENT.id = ID;
            cOMMANDE_CLIENT.date = date;
            cOMMANDE_CLIENT.prix_total = prix_total;
            return cOMMANDE_CLIENT;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété date dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime date
        {
            get
            {
                return this._date;
            }
            set
            {
                this.OndateChanging(value);
                this._date = value;
                this.OndateChanged();
                this.OnPropertyChanged("date");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prix_total dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal prix_total
        {
            get
            {
                return this._prix_total;
            }
            set
            {
                this.Onprix_totalChanging(value);
                this._prix_total = value;
                this.Onprix_totalChanged();
                this.OnPropertyChanged("prix_total");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _prix_total;
        partial void Onprix_totalChanging(decimal value);
        partial void Onprix_totalChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour ADRESSE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ADRESSE_CLIENT ADRESSE_CLIENT
        {
            get
            {
                return this._ADRESSE_CLIENT;
            }
            set
            {
                this._ADRESSE_CLIENT = value;
                this.OnPropertyChanged("ADRESSE_CLIENT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ADRESSE_CLIENT _ADRESSE_CLIENT;
        /// <summary>
        /// Il n'existe aucun commentaire pour CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CLIENT CLIENT
        {
            get
            {
                return this._CLIENT;
            }
            set
            {
                this._CLIENT = value;
                this.OnPropertyChanged("CLIENT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CLIENT _CLIENT;
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<COMMANDE_FOURNISSEUR> COMMANDE_FOURNISSEUR
        {
            get
            {
                return this._COMMANDE_FOURNISSEUR;
            }
            set
            {
                this._COMMANDE_FOURNISSEUR = value;
                this.OnPropertyChanged("COMMANDE_FOURNISSEUR");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<COMMANDE_FOURNISSEUR> _COMMANDE_FOURNISSEUR = new global::System.Data.Services.Client.DataServiceCollection<COMMANDE_FOURNISSEUR>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.COMMANDE_FOURNISSEUR dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("COMMANDE_FOURNISSEUR")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class COMMANDE_FOURNISSEUR : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet COMMANDE_FOURNISSEUR.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="date_generation">Valeur initiale de date_generation.</param>
        /// <param name="prix_total">Valeur initiale de prix_total.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static COMMANDE_FOURNISSEUR CreateCOMMANDE_FOURNISSEUR(global::System.Guid ID, global::System.DateTime date_generation, decimal prix_total)
        {
            COMMANDE_FOURNISSEUR cOMMANDE_FOURNISSEUR = new COMMANDE_FOURNISSEUR();
            cOMMANDE_FOURNISSEUR.id = ID;
            cOMMANDE_FOURNISSEUR.date_generation = date_generation;
            cOMMANDE_FOURNISSEUR.prix_total = prix_total;
            return cOMMANDE_FOURNISSEUR;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété date_generation dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime date_generation
        {
            get
            {
                return this._date_generation;
            }
            set
            {
                this.Ondate_generationChanging(value);
                this._date_generation = value;
                this.Ondate_generationChanged();
                this.OnPropertyChanged("date_generation");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _date_generation;
        partial void Ondate_generationChanging(global::System.DateTime value);
        partial void Ondate_generationChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété date_validation dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> date_validation
        {
            get
            {
                return this._date_validation;
            }
            set
            {
                this.Ondate_validationChanging(value);
                this._date_validation = value;
                this.Ondate_validationChanged();
                this.OnPropertyChanged("date_validation");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _date_validation;
        partial void Ondate_validationChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Ondate_validationChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété date_expedition dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> date_expedition
        {
            get
            {
                return this._date_expedition;
            }
            set
            {
                this.Ondate_expeditionChanging(value);
                this._date_expedition = value;
                this.Ondate_expeditionChanged();
                this.OnPropertyChanged("date_expedition");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _date_expedition;
        partial void Ondate_expeditionChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Ondate_expeditionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété date_reception dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> date_reception
        {
            get
            {
                return this._date_reception;
            }
            set
            {
                this.Ondate_receptionChanging(value);
                this._date_reception = value;
                this.Ondate_receptionChanged();
                this.OnPropertyChanged("date_reception");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _date_reception;
        partial void Ondate_receptionChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Ondate_receptionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété duree_expedition_estimee dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> duree_expedition_estimee
        {
            get
            {
                return this._duree_expedition_estimee;
            }
            set
            {
                this.Onduree_expedition_estimeeChanging(value);
                this._duree_expedition_estimee = value;
                this.Onduree_expedition_estimeeChanged();
                this.OnPropertyChanged("duree_expedition_estimee");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _duree_expedition_estimee;
        partial void Onduree_expedition_estimeeChanging(global::System.Nullable<decimal> value);
        partial void Onduree_expedition_estimeeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prix_total dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal prix_total
        {
            get
            {
                return this._prix_total;
            }
            set
            {
                this.Onprix_totalChanging(value);
                this._prix_total = value;
                this.Onprix_totalChanged();
                this.OnPropertyChanged("prix_total");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _prix_total;
        partial void Onprix_totalChanging(decimal value);
        partial void Onprix_totalChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_CLIENT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public COMMANDE_CLIENT COMMANDE_CLIENT
        {
            get
            {
                return this._COMMANDE_CLIENT;
            }
            set
            {
                this._COMMANDE_CLIENT = value;
                this.OnPropertyChanged("COMMANDE_CLIENT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private COMMANDE_CLIENT _COMMANDE_CLIENT;
        /// <summary>
        /// Il n'existe aucun commentaire pour FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FOURNISSEUR FOURNISSEUR
        {
            get
            {
                return this._FOURNISSEUR;
            }
            set
            {
                this._FOURNISSEUR = value;
                this.OnPropertyChanged("FOURNISSEUR");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private FOURNISSEUR _FOURNISSEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDER dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<COMMANDER> COMMANDER
        {
            get
            {
                return this._COMMANDER;
            }
            set
            {
                this._COMMANDER = value;
                this.OnPropertyChanged("COMMANDER");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<COMMANDER> _COMMANDER = new global::System.Data.Services.Client.DataServiceCollection<COMMANDER>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.COMMANDER dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id_commande_fournisseur
    /// id_produit
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("COMMANDER")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id_commande_fournisseur", "id_produit")]
    public partial class COMMANDER : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet COMMANDER.
        /// </summary>
        /// <param name="id_commande_fournisseur">Valeur initiale de id_commande_fournisseur.</param>
        /// <param name="id_produit">Valeur initiale de id_produit.</param>
        /// <param name="quantite">Valeur initiale de quantite.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static COMMANDER CreateCOMMANDER(global::System.Guid id_commande_fournisseur, global::System.Guid id_produit, decimal quantite)
        {
            COMMANDER cOMMANDER = new COMMANDER();
            cOMMANDER.id_commande_fournisseur = id_commande_fournisseur;
            cOMMANDER.id_produit = id_produit;
            cOMMANDER.quantite = quantite;
            return cOMMANDER;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_commande_fournisseur dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id_commande_fournisseur
        {
            get
            {
                return this._id_commande_fournisseur;
            }
            set
            {
                this.Onid_commande_fournisseurChanging(value);
                this._id_commande_fournisseur = value;
                this.Onid_commande_fournisseurChanged();
                this.OnPropertyChanged("id_commande_fournisseur");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id_commande_fournisseur;
        partial void Onid_commande_fournisseurChanging(global::System.Guid value);
        partial void Onid_commande_fournisseurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id_produit dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id_produit
        {
            get
            {
                return this._id_produit;
            }
            set
            {
                this.Onid_produitChanging(value);
                this._id_produit = value;
                this.Onid_produitChanged();
                this.OnPropertyChanged("id_produit");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id_produit;
        partial void Onid_produitChanging(global::System.Guid value);
        partial void Onid_produitChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété quantite dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal quantite
        {
            get
            {
                return this._quantite;
            }
            set
            {
                this.OnquantiteChanging(value);
                this._quantite = value;
                this.OnquantiteChanged();
                this.OnPropertyChanged("quantite");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _quantite;
        partial void OnquantiteChanging(decimal value);
        partial void OnquantiteChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public COMMANDE_FOURNISSEUR COMMANDE_FOURNISSEUR
        {
            get
            {
                return this._COMMANDE_FOURNISSEUR;
            }
            set
            {
                this._COMMANDE_FOURNISSEUR = value;
                this.OnPropertyChanged("COMMANDE_FOURNISSEUR");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private COMMANDE_FOURNISSEUR _COMMANDE_FOURNISSEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour PRODUIT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PRODUIT PRODUIT
        {
            get
            {
                return this._PRODUIT;
            }
            set
            {
                this._PRODUIT = value;
                this.OnPropertyChanged("PRODUIT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PRODUIT _PRODUIT;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.FOURNISSEUR dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("FOURNISSEUR")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class FOURNISSEUR : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet FOURNISSEUR.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="nom">Valeur initiale de nom.</param>
        /// <param name="email">Valeur initiale de email.</param>
        /// <param name="phone">Valeur initiale de phone.</param>
        /// <param name="password">Valeur initiale de password.</param>
        /// <param name="adresse">Valeur initiale de adresse.</param>
        /// <param name="ville">Valeur initiale de ville.</param>
        /// <param name="code_postal">Valeur initiale de code_postal.</param>
        /// <param name="pays">Valeur initiale de pays.</param>
        /// <param name="supprime">Valeur initiale de supprime.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FOURNISSEUR CreateFOURNISSEUR(global::System.Guid ID, string nom, string email, string phone, string password, string adresse, string ville, string code_postal, string pays, bool supprime)
        {
            FOURNISSEUR fOURNISSEUR = new FOURNISSEUR();
            fOURNISSEUR.id = ID;
            fOURNISSEUR.nom = nom;
            fOURNISSEUR.email = email;
            fOURNISSEUR.phone = phone;
            fOURNISSEUR.password = password;
            fOURNISSEUR.adresse = adresse;
            fOURNISSEUR.ville = ville;
            fOURNISSEUR.code_postal = code_postal;
            fOURNISSEUR.pays = pays;
            fOURNISSEUR.supprime = supprime;
            return fOURNISSEUR;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nom dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                this._nom = value;
                this.OnnomChanged();
                this.OnPropertyChanged("nom");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété email dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this._email = value;
                this.OnemailChanged();
                this.OnPropertyChanged("email");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété phone dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string phone
        {
            get
            {
                return this._phone;
            }
            set
            {
                this.OnphoneChanging(value);
                this._phone = value;
                this.OnphoneChanged();
                this.OnPropertyChanged("phone");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _phone;
        partial void OnphoneChanging(string value);
        partial void OnphoneChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété password dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                this.OnpasswordChanging(value);
                this._password = value;
                this.OnpasswordChanged();
                this.OnPropertyChanged("password");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _password;
        partial void OnpasswordChanging(string value);
        partial void OnpasswordChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété adresse dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string adresse
        {
            get
            {
                return this._adresse;
            }
            set
            {
                this.OnadresseChanging(value);
                this._adresse = value;
                this.OnadresseChanged();
                this.OnPropertyChanged("adresse");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _adresse;
        partial void OnadresseChanging(string value);
        partial void OnadresseChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété ville dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ville
        {
            get
            {
                return this._ville;
            }
            set
            {
                this.OnvilleChanging(value);
                this._ville = value;
                this.OnvilleChanged();
                this.OnPropertyChanged("ville");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ville;
        partial void OnvilleChanging(string value);
        partial void OnvilleChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété code_postal dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string code_postal
        {
            get
            {
                return this._code_postal;
            }
            set
            {
                this.Oncode_postalChanging(value);
                this._code_postal = value;
                this.Oncode_postalChanged();
                this.OnPropertyChanged("code_postal");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _code_postal;
        partial void Oncode_postalChanging(string value);
        partial void Oncode_postalChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété pays dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string pays
        {
            get
            {
                return this._pays;
            }
            set
            {
                this.OnpaysChanging(value);
                this._pays = value;
                this.OnpaysChanged();
                this.OnPropertyChanged("pays");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _pays;
        partial void OnpaysChanging(string value);
        partial void OnpaysChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété supprime dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool supprime
        {
            get
            {
                return this._supprime;
            }
            set
            {
                this.OnsupprimeChanging(value);
                this._supprime = value;
                this.OnsupprimeChanged();
                this.OnPropertyChanged("supprime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _supprime;
        partial void OnsupprimeChanging(bool value);
        partial void OnsupprimeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDE_FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<COMMANDE_FOURNISSEUR> COMMANDE_FOURNISSEUR
        {
            get
            {
                return this._COMMANDE_FOURNISSEUR;
            }
            set
            {
                this._COMMANDE_FOURNISSEUR = value;
                this.OnPropertyChanged("COMMANDE_FOURNISSEUR");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<COMMANDE_FOURNISSEUR> _COMMANDE_FOURNISSEUR = new global::System.Data.Services.Client.DataServiceCollection<COMMANDE_FOURNISSEUR>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour PRODUIT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PRODUIT> PRODUIT
        {
            get
            {
                return this._PRODUIT;
            }
            set
            {
                this._PRODUIT = value;
                this.OnPropertyChanged("PRODUIT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PRODUIT> _PRODUIT = new global::System.Data.Services.Client.DataServiceCollection<PRODUIT>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.IMAGE dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("IMAGE")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class IMAGE : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet IMAGE.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="url">Valeur initiale de url.</param>
        /// <param name="img_hauteur">Valeur initiale de img_hauteur.</param>
        /// <param name="img_largeur">Valeur initiale de img_largeur.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static IMAGE CreateIMAGE(global::System.Guid ID, string url, decimal img_hauteur, decimal img_largeur)
        {
            IMAGE iMAGE = new IMAGE();
            iMAGE.id = ID;
            iMAGE.url = url;
            iMAGE.img_hauteur = img_hauteur;
            iMAGE.img_largeur = img_largeur;
            return iMAGE;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété url dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string url
        {
            get
            {
                return this._url;
            }
            set
            {
                this.OnurlChanging(value);
                this._url = value;
                this.OnurlChanged();
                this.OnPropertyChanged("url");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _url;
        partial void OnurlChanging(string value);
        partial void OnurlChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété img_hauteur dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal img_hauteur
        {
            get
            {
                return this._img_hauteur;
            }
            set
            {
                this.Onimg_hauteurChanging(value);
                this._img_hauteur = value;
                this.Onimg_hauteurChanged();
                this.OnPropertyChanged("img_hauteur");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _img_hauteur;
        partial void Onimg_hauteurChanging(decimal value);
        partial void Onimg_hauteurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété img_largeur dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal img_largeur
        {
            get
            {
                return this._img_largeur;
            }
            set
            {
                this.Onimg_largeurChanging(value);
                this._img_largeur = value;
                this.Onimg_largeurChanged();
                this.OnPropertyChanged("img_largeur");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _img_largeur;
        partial void Onimg_largeurChanging(decimal value);
        partial void Onimg_largeurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour PRODUIT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PRODUIT PRODUIT
        {
            get
            {
                return this._PRODUIT;
            }
            set
            {
                this._PRODUIT = value;
                this.OnPropertyChanged("PRODUIT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PRODUIT _PRODUIT;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour DADModel.PRODUIT dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PRODUIT")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class PRODUIT : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet PRODUIT.
        /// </summary>
        /// <param name="ID">Valeur initiale de id.</param>
        /// <param name="reference">Valeur initiale de reference.</param>
        /// <param name="nom">Valeur initiale de nom.</param>
        /// <param name="marque">Valeur initiale de marque.</param>
        /// <param name="prix">Valeur initiale de prix.</param>
        /// <param name="stock">Valeur initiale de stock.</param>
        /// <param name="disponible">Valeur initiale de disponible.</param>
        /// <param name="supprime">Valeur initiale de supprime.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PRODUIT CreatePRODUIT(global::System.Guid ID, string reference, string nom, string marque, decimal prix, decimal stock, bool disponible, bool supprime)
        {
            PRODUIT pRODUIT = new PRODUIT();
            pRODUIT.id = ID;
            pRODUIT.reference = reference;
            pRODUIT.nom = nom;
            pRODUIT.marque = marque;
            pRODUIT.prix = prix;
            pRODUIT.stock = stock;
            pRODUIT.disponible = disponible;
            pRODUIT.supprime = supprime;
            return pRODUIT;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété reference dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string reference
        {
            get
            {
                return this._reference;
            }
            set
            {
                this.OnreferenceChanging(value);
                this._reference = value;
                this.OnreferenceChanged();
                this.OnPropertyChanged("reference");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _reference;
        partial void OnreferenceChanging(string value);
        partial void OnreferenceChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nom dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                this._nom = value;
                this.OnnomChanged();
                this.OnPropertyChanged("nom");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété marque dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string marque
        {
            get
            {
                return this._marque;
            }
            set
            {
                this.OnmarqueChanging(value);
                this._marque = value;
                this.OnmarqueChanged();
                this.OnPropertyChanged("marque");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _marque;
        partial void OnmarqueChanging(string value);
        partial void OnmarqueChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prix dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal prix
        {
            get
            {
                return this._prix;
            }
            set
            {
                this.OnprixChanging(value);
                this._prix = value;
                this.OnprixChanged();
                this.OnPropertyChanged("prix");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _prix;
        partial void OnprixChanging(decimal value);
        partial void OnprixChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété stock dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal stock
        {
            get
            {
                return this._stock;
            }
            set
            {
                this.OnstockChanging(value);
                this._stock = value;
                this.OnstockChanged();
                this.OnPropertyChanged("stock");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _stock;
        partial void OnstockChanging(decimal value);
        partial void OnstockChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété description dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété disponible dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool disponible
        {
            get
            {
                return this._disponible;
            }
            set
            {
                this.OndisponibleChanging(value);
                this._disponible = value;
                this.OndisponibleChanged();
                this.OnPropertyChanged("disponible");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _disponible;
        partial void OndisponibleChanging(bool value);
        partial void OndisponibleChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété supprime dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool supprime
        {
            get
            {
                return this._supprime;
            }
            set
            {
                this.OnsupprimeChanging(value);
                this._supprime = value;
                this.OnsupprimeChanged();
                this.OnPropertyChanged("supprime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _supprime;
        partial void OnsupprimeChanging(bool value);
        partial void OnsupprimeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour COMMANDER dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<COMMANDER> COMMANDER
        {
            get
            {
                return this._COMMANDER;
            }
            set
            {
                this._COMMANDER = value;
                this.OnPropertyChanged("COMMANDER");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<COMMANDER> _COMMANDER = new global::System.Data.Services.Client.DataServiceCollection<COMMANDER>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour FOURNISSEUR dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FOURNISSEUR FOURNISSEUR
        {
            get
            {
                return this._FOURNISSEUR;
            }
            set
            {
                this._FOURNISSEUR = value;
                this.OnPropertyChanged("FOURNISSEUR");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private FOURNISSEUR _FOURNISSEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour IMAGE dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<IMAGE> IMAGE
        {
            get
            {
                return this._IMAGE;
            }
            set
            {
                this._IMAGE = value;
                this.OnPropertyChanged("IMAGE");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<IMAGE> _IMAGE = new global::System.Data.Services.Client.DataServiceCollection<IMAGE>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour CATEGORIE dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CATEGORIE> CATEGORIE
        {
            get
            {
                return this._CATEGORIE;
            }
            set
            {
                this._CATEGORIE = value;
                this.OnPropertyChanged("CATEGORIE");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CATEGORIE> _CATEGORIE = new global::System.Data.Services.Client.DataServiceCollection<CATEGORIE>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
